title: Mondy Ayman | QA & Automation Engineer
email: bourham2018@gmail.com
description: >-
  Computer Science Graduate (2024) | QA & Automation Engineer | CI/CD Advocate
baseurl: ""
url: "https://mondybourham.github.io"
github_username: MondyBourham

# Build settings
theme: minima
plugins:
  - jekyll-seo-tag

# Minima theme overrides
minima:
  skin: auto  # enables system dark mode
  social_links:
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/mondy-bourham" }
    - { platform: github, user_url: "https://github.com/MondyBourham" }

# Custom defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
